### PR TITLE
Add optional face recognition

### PR DESCRIPTION
**Pull request by sharpner**
this server will have a lot more dependencies than the usual one.

So currently there is application.go which, when build, contains only the three default resize types.

by using ```go get github.com/VoycerAG/gridfs-image-server/cmd/advanced``` you will get the new one.

### CODE REVIEW

**Comment by sharpner** [comment]
waits on https://github.com/muesli/smartcrop/pull/22

**Comment by sharpner** [comment]
So I'm done for now. I am still not absolutely happy with the results, but for the moment its the best I can think of.

We now have the same face result in every size. 

In order to finalize the results to be perfect, we need to figure out a way to include the face optimal within the target bounds. 

I could not figure out a calculation that works for landscape, as well as portrait mode (for both input and outputs).

Therefore we now always get face results (same false positives on butts etc :P) but they aren't always centered in the image.

E.G.:
50x50_0019
But they can be:
50x50_0018
It depends mostly on the input. 

Other results that could be improved:
50x50_0013
50x50_0014
50x50_0015
200x400_0030

Its worse if the input is in really high portrait (374x739) and the output should be small landscape:
200x400_0056

Sometimes even the eyes are missing.

**Comment by sharpner** [comment]
Additionally, if the resizer does not find a face, it will simply crop the image instead.

**Comment by gruberro** [comment]
Is there a way to test it, I mean have you already installed this image server version on some stage?

**Comment by sharpner** [comment]
we could finally improve our deployment to let it install branches.

Otherwise: This PR is fully backwards compatible, we could also just merge it, and update our deployment to install the necessary deps.

**Pull request merged**
